export const data = {
    title: 'Pracownia endoskopii',
    alt: 'endo_workshop_clinic',
    text0: '',
    text: 'Wykonujemy badania kolonoskopii w znieczuleniu ogólnym pod nadzorem specjalisty anestezjologa. Kolonoskopia jest badaniem, polegającym na oglądaniu wnętrza jelita grubego za pomocąwprowadzonego przez odbyt specjalnego wziernika zakończonego kamerą, który przekazuje obraz do komputera. Do tego celu służy giętki aparat o średnicy 10 mm zwany kolonoskopem. Poprzez aparat podaje się powietrze, aby dzięki rozdęciu jelita uwidocznić jego ścianę i prawidłowo ocenić stan błony śluzowej. w trakcie badania, jeżeli jest taka potrzeba, pobiera się wycinki błony śluzowej do badania histopatologicznego, czyli oceny tkanek pod mikroskopem. W czasie badaniamożna również wykonać proste zabiegi endoskopowe np. usunięcia polipów. Badanie - kolonoskopia jest obecnie jedną z najskuteczniejszych metod wczesnego diagnozowanianowotworów przewodu pokarmowego. Kolonoskopia w centrum usług medycznych świdmed badania wykonywane w naszej pracowni endoskopowej zapewniają pacjentom komfort, zachowanie intymności oraz pełne bezpieczeństwo. aby maksymalnie zmniejszyć dyskomfort wynikający ze specyfiki badania, wykonujemy je w znieczuleniu ogólnym, tzw. sedacji. Cały zabieg odbywa się pod nadzorem lekarza specjalisty anestezjologa i pielęgniarki anestezjologicznej. całe badanie wykonywane jest przez wysoko wykwalifikowany personel medyczny (dwóch lekarzy i dwie pielęgniarki) z pełnym zabezpieczeniem w najlepszej jakości sprzęt medyczny. Każdy pacjent przed planowanym badaniem lub zabiegiem jest informowany o jego rodzaju i możliwych powikłaniach. Badanie trwa od 20 do 40 minut. Opis badania dostępny jest od razu po jego wykonaniu. w wypadku, gdy pobierano materiał do badania histopatologicznego, wynik badania gotowy jest po 3 tygodniach',
    url: '/images/cards/endo_workshop.jpg',
    items0: [],
    items: ['na kolonoskopię należy zgłosić się 30 min. przed planowaną godziną badania wrazz pełnoletnią osobą towarzyszącą',
     '24 godziny po badaniu nie wolno prowadzić samochodu',
     'po wykonaniu badania pacjent przebywa pod obserwacją około 2-3 godziny, po czym pod opieką osoby pełnoletniej może udać się do domu' ,
     'pacjenci z rozpoznanymi chorobami przewlekłymi (choroby układu krążenia, cukrzyca lub inne), stosujący leki (leki wpływające na krzepliwość krwi), proszeni są o poinformowanie o tym podczas rejestracji na badani',
     'w przypadku pojawienia się po badaniu silnych dolegliwości bólowych jamy brzusznej, gorączki, krwawienia lub innych niepokojących pacjenta objawów prosimy o kontakt telefoniczny z rejestracją']
}